org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Java
java_version=25

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=26.2.1
maven_group=me.simplesort

# Dependencies
cloth_config_version=26.2.155
fabric_api_version=0.155.2+26.2
mod_menu_version=20.0.1