org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Java
java_version=21

# Fabric Properties
minecraft_version=1.21
loader_version=0.17.3
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=1.21.0.1
maven_group=me.simplesort

# Dependencies
cloth_config_version=15.0.140
fabric_api_version=0.102.0+1.21
mod_menu_version=11.0.4