org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Java
java_version=21

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=26.1.2.2
maven_group=me.simplesort

# Dependencies
cloth_config_version=26.1.154
fabric_api_version=0.148.0+26.1.2
mod_menu_version=18.0.0-alpha.8